export * as Book from "./Book.ts"
export * as Chapter from "./Chapter.ts"
export * as Result from "./Result.ts"
export * as Task from "./Task.ts"
export * as User from "./User.ts"
export * as Link from "./Link.ts"
export * as Record from "./Record.ts"
